### ISSUE TITLE
Error launching the project 

### ISSUE THREAD

**Issue by masterviana** [AlaaMezian/NodeJs-backend-structure#2]
I quite like the project folder structure, however its not able to run it after clone, it's missing some depencies.

Error: Cannot find module './termsAndConditionRouter'

It's nice using that just as template.

**Comment by AlaaMezian** [comment]
Hello masterViana 
I'm happy that you like the project I fixed the issues please try now and tell me 
also sorry for the late reply but I didn't notice your issue until now.
